; Uncomment and configure mode https://xdebug.org/docs/all_settings#xdebug.mode
;zend_extension=xdebug.so
;xdebug.mode=profile
;xdebug.start_with_request=trigger
;xdebug.output_dir=/var/log/xdebug
;xdebug.profiler_output_name=cachegrind.out.%p
